version: '3'
services:
  backend:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    depends_on:
      - database
    links:
      - database
    ports:
      - 8080:8080
    environment:
      MONGODB_HOST: database