version: '3'
services:
  database:
    image: mongo:latest
    container_name: 'mongo-container'
    environment:
      MONGO_INITDB_DATABASE: companyon
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: database
