apiVersion: v1
kind: Service
metadata:
  labels:
    env: {{ .Values.env }}
  name: companyon-mongodb-service-{{ .Values.env }}
  namespace: companyon
spec:
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  selector:
    app: companyon
    env: {{ .Values.env }}
    tier: mongodb
  type: ClusterIP
